name: Manager Tests

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Change working directory
        run: cd ./manager

      # Print everything in the current directory
      - name: List files
        run: ls -a

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test
